# §B5 Background-Fit scores from the Colab run (wording APPROVED 2026-06-29). {company: [bg_fit, loop, basis]}
BG_FIT = {
    "9amhealth": [8, "yes", "connected scale feeds readings"],
    "affect therapeutics": [8, "no", "ongoing retention-driven treatment program, weekly therapy"],
    "allara health": [7, "no", "monthly subscription PCOS care, app messaging + video follow-ups"],
    "angle health": [4, "no", "interact around enrollment/claims/denials/renewal admin"],
    "berry street": [5, "no", "scheduled dietitian visits + supportive app around care episodes"],
    "bicycle health": [8, "no", "ongoing med management, clinician check-ins, therapy/support groups"],
    "counsel health": [4, "no", "episodic on-demand $29 visit + 90 days messaging"],
    "culina health": [6, "no", "recurring virtual nutrition counseling + app meal logging"],
    "cylinder health": [4, "no", "episodic GI-care access, virtual visits, at-home kits"],
    "diana health": [4, "no", "episodic care-coordination: appointments, messaging, results"],
    "equip health": [7, "no", "structured multi-month eating-disorder program, sessions + meal support"],
    "familywell health": [7, "no", "ongoing weekly coaching/therapy/psychiatry during treatment"],
    "fay": [7, "no", "recurring dietitian appts + async chat + optional meal logging"],
    "foodsmart": [7, "no", "ongoing nutrition-support: meal planning, recurring dietitian"],
    "function health": [4, "no", "annual/twice-yearly lab testing + results review"],
    "grow therapy": [7, "no", "recurring therapy appointments, session-based engagement"],
    "insidetracker": [4, "no", "episodic bloodwork upload/retest a few times a year"],
    "jasper health": [7, "no", "recurring phase-based cancer navigation, weekly 1-on-1 coaching"],
    "levels health": [9, "yes", "CGM + app: see glucose -> act -> see reflected -> repeat"],
    "nourish": [8, "no", "recurring telehealth dietitian + between-session app/messaging over months"],
    "oova": [7, "yes", "repeated hormone testing, review in-app, act, repeat across cycles"],
    "oshi health": [5, "no", "mostly insurance-billed GI care, occasional visits + messaging"],
    "oula": [4, "no", "episode-driven maternity care around pregnancy/delivery/postpartum"],
    "outcomes4me": [5, "no", "intermittent app use for guidance/records/trial matching"],
    "pelago": [8, "no", "structured time-bounded program, weekly coaching + daily check-ins"],
    "pomelo care": [7, "no", "24/7 messaging/calls/video with care team across pregnancy/postpartum"],
    "rula health": [7, "no", "recurring therapy/psychiatry, often weekly"],
    "season health": [7, "no", "nutrition care touchpoints, dietitian visits, meal planning, food benefit"],
    "signos": [9, "yes", "tight daily glucose-tracking loop via CGM app, weekly guidance, adjust"],
    "solace health": [4, "no", "episodic care navigation, claims, appointments, insurance help"],
    "summer health": [7, "no", "on-demand pediatric text visits + occasional follow-ups"],
    "tia": [4, "no", "annual preventive exams + episodic clinic visits"],
    "visana health": [5, "no", "appointment-based longitudinal women's health, portal messaging"],
    "vivante health": [4, "no", "GIThrive program around intake/symptom-tracking/episodes"],
    "waymark": [4, "no", "intermittent care-navigation/check-ins, start/stop anytime"],
    "wellist": [4, "no", "as-needed care-navigation/support-resource lookup"],
    "zoe": [8, "no", "frequent habitual daily photo/food logging + nutrition insights"],
}
